apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 800Mi
  accessModes:
  - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-local-image
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - bin/sh
            - -c
            - pgrep mariadb && pgrep telegraf
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - name: mysql-port
          containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-cnf
          mountPath: /etc/my.cnf.d
        - name: telegraf
          mountPath: /etc/telegraf
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-cnf
        configMap:
          name: mysql-config
      - name: telegraf
        configMap:
          name: telegraf-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql.cnf: |
    [mysqld]
    user = root
    port = 3306
    datadir = /var/lib/mysql
    bind-address = 0.0.0.0
    skip-networking = false

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: mysql-port
