apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx-local-image
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
              - bin/sh
              - -c
              - pgrep nginx && pgrep sshd && pgrep telegraf
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: ssh
              containerPort: 22
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/http.d
            - name: sites-volume
              mountPath: /etc/nginx/html
            - name: telegraf
              mountPath: /etc/telegraf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            items:
              - key: my-nginx.conf
                path: my-nginx.conf
        - name: sites-volume
          configMap:
            name: nginx-config
            items:
              - key: index_hello.html
                path: index_hello.html
        - name: telegraf
          configMap:
            name: telegraf-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  my-nginx.conf: |
    server {
    	listen 80;
    	listen [::]:80;
    	server_name _;
    	return 301 https://$host$request_uri;
    }

    server {
    	listen 443      ssl;
    	listen [::]:443 ssl;

    	server_name localhost;

    	ssl_certificate /opt/server.pem;
    	ssl_certificate_key /opt/server.pem;

    	location / {
    		root /etc/nginx/html/;
    		index index_hello.html;

    		try_files $uri $uri/ =404;
    	}

    	location /wordpress {
    		return 307 https://$host:5050;
    	}

    	location /phpmyadmin {
                rewrite /phpmyadmin/(.*) /$1 break;
    		proxy_pass https://$host:5000;
    	}
    }
  index_hello.html: |
    <h1>Hello</h1>
    <h2>ft_services</h2>
    <h3>The server is runnning</h3>

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: entry-point
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
    - name: ssh
      port: 22
      targetPort: ssh
  type: LoadBalancer
